// SPDX-License-Identifier: Apache-2.0
// The brain view: every symbol of a repository as a particle of a brain, every relationship as a
// fibre between two of them, every memory as a beacon above the code it describes.
//
// Plain WebGL 1 and no library, because the page makes no request of any kind: the Content
// Security Policy in its head forbids it, so nothing a repository holds can leave the machine.
// All text from the repository is written with textContent, never parsed as HTML.
'use strict';
(function () {
  const $ = (id) => document.getElementById(id);
  const LANG = document.documentElement.lang === 'es' ? 'es' : 'en';
  const STRINGS = {
    en: {
      search: 'Search symbols, files and memories', files: 'files', symbols: 'symbols',
      edges: 'connections', memories: 'memories', stale: 'stale', regions: 'Regions', view: 'View',
      tEdges: 'Fibres', tSignals: 'Signals', tMemories: 'Memories', tCortex: 'Cortex',
      tLabels: 'Labels', tRotate: 'Rotate', calledBy: 'Called by', calls: 'Calls',
      sig: 'Signature', mems: 'Memories', copyCtx: 'Copy context for an agent',
      copyLoc: 'Copy location', copied: 'Copied to the clipboard', copyFail: 'Could not copy',
      focus: 'Fly to it', more: (n) => `+${n} more`, noMatch: 'No match',
      cut: (a, b) => `Showing the ${a} most connected of ${b} symbols.`,
      offline: 'Generated by pn-ultramemory. Nothing on this page reaches the network.',
      empty: 'This index holds no symbols yet. Run <code>pn-ultramemory index</code> in the repository, then <code>pn-ultramemory brain</code> again.',
      noGl: 'This browser has WebGL turned off, and the brain view needs it to draw.',
      hint: 'drag to turn · right-drag to move · scroll to zoom · <kbd>/</kbd> search · <kbd>Esc</kbd> clear',
      tests: 'Tests live in the cerebellum.', test: 'test', memory: 'memory',
      anchored: 'Anchored to', notDrawn: 'not drawn', unanchored: 'Not anchored to any code',
      staleWhy: 'stale: the code it describes changed since it was written',
      ctxCalledBy: 'called by', ctxCalls: 'calls', ctxNext: 'next',
      noMem: 'No memories yet: pn-ultramemory remember decision "…" --about <symbol> adds one, anchored to the code.',
      memCount: (n) => (n === 1 ? '1 memory' : `${n} memories`),
    },
    es: {
      search: 'Busca símbolos, archivos y memorias', files: 'archivos', symbols: 'símbolos',
      edges: 'conexiones', memories: 'memorias', stale: 'obsoletas', regions: 'Regiones', view: 'Vista',
      tEdges: 'Fibras', tSignals: 'Señales', tMemories: 'Memorias', tCortex: 'Corteza',
      tLabels: 'Etiquetas', tRotate: 'Girar', calledBy: 'Lo llaman', calls: 'Llama a',
      sig: 'Firma', mems: 'Memorias', copyCtx: 'Copiar contexto para un agente',
      copyLoc: 'Copiar ubicación', copied: 'Copiado al portapapeles', copyFail: 'No se pudo copiar',
      focus: 'Volar hasta aquí', more: (n) => `${n} más`, noMatch: 'Sin resultados',
      cut: (a, b) => `Se muestran los ${a} símbolos más conectados de ${b}.`,
      offline: 'Generado por pn-ultramemory. Nada en esta página sale a la red.',
      empty: 'Este índice aún no tiene símbolos. Ejecuta <code>pn-ultramemory index</code> en el repositorio y luego <code>pn-ultramemory brain</code> otra vez.',
      noGl: 'Este navegador tiene WebGL desactivado, y la vista del cerebro lo necesita para dibujar.',
      hint: 'arrastra para girar · clic derecho para mover · rueda para acercar · <kbd>/</kbd> buscar · <kbd>Esc</kbd> limpiar',
      tests: 'Las pruebas viven en el cerebelo.', test: 'prueba', memory: 'memoria',
      anchored: 'Anclada a', notDrawn: 'no dibujado', unanchored: 'No está anclada a ningún código',
      staleWhy: 'obsoleta: el código que describe cambió después de escribirla',
      ctxCalledBy: 'lo llaman', ctxCalls: 'llama a', ctxNext: 'siguiente',
      noMem: 'Aún no hay memorias: pn-ultramemory remember decision "…" --about <símbolo> añade una, anclada al código.',
      memCount: (n) => (n === 1 ? '1 memoria' : `${n} memorias`),
    },
  };
  const S = STRINGS[LANG];
  const fmt = (n) => Number(n || 0).toLocaleString(LANG);

  let DATA = null;
  try { DATA = JSON.parse($('brain-data').textContent); } catch (_) { DATA = null; }
  if (!DATA || !Array.isArray(DATA.nodes)) DATA = { repo: '', nodes: [], edges: [], memories: [], regions: [], paths: [], kinds: [] };

  // ---------------------------------------------------------------- the model
  const N = DATA.nodes.length;
  const ID = new Array(N), NAME = new Array(N), QUAL = new Array(N), KIND = new Uint8Array(N);
  const REGION = new Uint16Array(N), PATH = new Uint32Array(N), LINE = new Uint32Array(N);
  const SIG = new Array(N), DOC = new Array(N), PUB = new Uint8Array(N), TEST = new Uint8Array(N);
  const TEST_PATH = /(^|\/)(tests?|__tests__|specs?|testing|fixtures)(\/|$)|(_test|\.test|\.spec|_spec|Test|Tests)\.[A-Za-z]+$|(^|\/)test_[^/]*$/;
  DATA.nodes.forEach((row, i) => {
    ID[i] = String(row[0]); NAME[i] = String(row[1] || ''); QUAL[i] = String(row[2] || '') || NAME[i];
    KIND[i] = row[3] | 0; REGION[i] = row[4] | 0; PATH[i] = row[5] | 0; LINE[i] = row[6] | 0;
    SIG[i] = String(row[7] || ''); DOC[i] = String(row[8] || ''); PUB[i] = row[9] ? 1 : 0;
    const path = DATA.paths[PATH[i]] || '';
    TEST[i] = TEST_PATH.test(path) || /(^|::|\.)tests?(::|\.)/.test(QUAL[i]) ? 1 : 0;
  });
  const kindName = (i) => (DATA.kinds && DATA.kinds[KIND[i]]) || 'symbol';
  const pathOf = (i) => DATA.paths[PATH[i]] || '';
  const BIG_KINDS = new Set(['class', 'struct', 'interface', 'enum', 'type']);

  const E = Math.floor((DATA.edges || []).length / 4);
  const ESRC = new Uint32Array(E), EDST = new Uint32Array(E), ECONF = new Uint8Array(E);
  const OUT = Array.from({ length: N }, () => []), IN = Array.from({ length: N }, () => []);
  for (let e = 0; e < E; e++) {
    const s = DATA.edges[e * 4], d = DATA.edges[e * 4 + 1];
    ESRC[e] = s; EDST[e] = d; ECONF[e] = DATA.edges[e * 4 + 3] | 0;
    if (s < N && d < N) { OUT[s].push(e); IN[d].push(e); }
  }
  const DEG = new Uint32Array(N);
  for (let i = 0; i < N; i++) DEG[i] = OUT[i].length + IN[i].length;

  const MEM = (DATA.memories || []).map((m) => ({
    id: m[0], kind: String(m[1] || ''), text: String(m[2] || ''), stale: !!m[3], by: String(m[4] || ''),
    anchors: (m[5] || []).filter((a) => a < N), about: m[6] || [], pos: [0, 0, 0],
  }));
  const MEM_OF = Array.from({ length: N }, () => []);
  MEM.forEach((m, k) => m.anchors.forEach((a) => MEM_OF[a].push(k)));

  const R = DATA.regions.length;
  const REGION_SIZE = new Uint32Array(R);
  for (let i = 0; i < N; i++) REGION_SIZE[REGION[i]]++;

  // ---------------------------------------------------------------- colour
  const PALETTE = ['#4cc9f0', '#b388ff', '#ff6ec7', '#ffd166', '#06d6a0', '#ff8c42', '#7bdff2',
    '#c3f584', '#f72585', '#a0c4ff', '#ffadad', '#9b5de5', '#00f5d4', '#fee440'];
  function hexRgb(hex) { const v = parseInt(hex.slice(1), 16); return [(v >> 16 & 255) / 255, (v >> 8 & 255) / 255, (v & 255) / 255]; }
  function hslRgb(h, s, l) {
    const a = s * Math.min(l, 1 - l);
    const f = (n) => { const k = (n + h * 12) % 12; return l - a * Math.max(-1, Math.min(k - 3, 9 - k, 1)); };
    return [f(0), f(8), f(4)];
  }
  const regionOrder = Array.from({ length: R }, (_, r) => r).sort((a, b) => REGION_SIZE[b] - REGION_SIZE[a] || a - b);
  const REGION_RGB = new Array(R);
  regionOrder.forEach((r, k) => { REGION_RGB[r] = k < PALETTE.length ? hexRgb(PALETTE[k]) : hslRgb((k * 0.618034) % 1, 0.75, 0.66); });
  const rgbCss = (c) => `rgb(${Math.round(c[0] * 255)},${Math.round(c[1] * 255)},${Math.round(c[2] * 255)})`;
  const CALLS_RGB = hexRgb('#5ee7ff'), CALLED_RGB = hexRgb('#ffa45e');
  const MEM_RGB = hexRgb('#ffd166'), STALE_RGB = hexRgb('#ff4d6d');

  // ---------------------------------------------------------------- the shape of a brain
  // Two hemispheres either side of a fissure, flatter underneath, and a cerebellum behind and
  // below them. Coordinates: x across, y up, z from the back (-) to the front (+).
  const HEMI = { x: 0.37, y: 0.06, z: 0, rx: 0.40, ry: 0.56, ryb: 0.40, rz: 0.88 };
  const CERE = { x: 0, y: -0.40, z: -0.56, rx: 0.50, ry: 0.22, rz: 0.30 };
  const FISSURE = 0.035;
  function hemiNorm(x, y, z, h) {
    const dx = (x - h * HEMI.x) / HEMI.rx, dy = (y - HEMI.y) / (y < HEMI.y ? HEMI.ryb : HEMI.ry), dz = (z - HEMI.z) / HEMI.rz;
    return Math.sqrt(dx * dx + dy * dy + dz * dz);
  }
  function cereNorm(x, y, z) {
    const dx = (x - CERE.x) / CERE.rx, dy = (y - CERE.y) / CERE.ry, dz = (z - CERE.z) / CERE.rz;
    return Math.sqrt(dx * dx + dy * dy + dz * dz);
  }
  // Keeps a point inside its part of the brain: a shell of the hemisphere for code, so the
  // particles form a cortex and the fibres run through the white matter, or anywhere inside the
  // cerebellum for tests.
  function constrain(P, o, home) {
    let x = P[o], y = P[o + 1], z = P[o + 2];
    if (home === 0) {
      const n = cereNorm(x, y, z);
      if (n > 0.95) { const s = 0.95 / n; x = CERE.x + (x - CERE.x) * s; y = CERE.y + (y - CERE.y) * s; z = CERE.z + (z - CERE.z) * s; }
    } else {
      if (home * x < FISSURE) x = home * FISSURE;
      const n = hemiNorm(x, y, z, home);
      const cx = home * HEMI.x;
      let s = 1;
      if (n > 0.97) s = 0.97 / n; else if (n < 0.6 && n > 1e-6) s = 0.6 / n;
      if (s !== 1) { x = cx + (x - cx) * s; y = HEMI.y + (y - HEMI.y) * s; z = HEMI.z + (z - HEMI.z) * s; }
      if (home * x < FISSURE) x = home * FISSURE;
    }
    P[o] = x; P[o + 1] = y; P[o + 2] = z;
  }

  // Seeded, so the same repository always grows the same brain.
  function hashString(s) { let h = 2166136261 >>> 0; for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); } return h >>> 0; }
  function rng(seed) {
    let a = seed >>> 0;
    return () => { a = (a + 0x6D2B79F5) >>> 0; let t = a; t = Math.imul(t ^ (t >>> 15), t | 1); t ^= t + Math.imul(t ^ (t >>> 7), t | 61); return ((t ^ (t >>> 14)) >>> 0) / 4294967296; };
  }
  const rand = rng(hashString(String(DATA.repo || 'brain')));
  const gauss = () => Math.sqrt(-2 * Math.log(Math.max(1e-9, rand()))) * Math.cos(2 * Math.PI * rand());

  // A home for every region: code regions in mirrored pairs over the two hemispheres, the
  // largest first and highest, test regions side by side in the cerebellum.
  const HOME = new Int8Array(N);
  const ANCHOR = new Float32Array(R * 3);
  const regionHome = new Int8Array(R);
  {
    const testCount = new Uint32Array(R);
    for (let i = 0; i < N; i++) if (TEST[i]) testCount[REGION[i]]++;
    const code = regionOrder.filter((r) => testCount[r] * 2 < REGION_SIZE[r]);
    const tests = regionOrder.filter((r) => testCount[r] * 2 >= REGION_SIZE[r]);
    const pairs = Math.max(1, Math.ceil(code.length / 2));
    code.forEach((r, k) => {
      const j = Math.floor(k / 2), h = k % 2 === 0 ? 1 : -1;
      const y = 0.95 - 1.5 * (j + 0.5) / pairs;
      const rad = Math.sqrt(Math.max(0, 1 - y * y));
      const phi = j * 2.399963 + 0.6;
      const dx = 0.35 + 0.65 * Math.abs(Math.cos(phi)) * rad, dz = Math.sin(phi) * rad;
      regionHome[r] = h;
      ANCHOR[r * 3] = h * HEMI.x + h * dx * HEMI.rx * 0.8;
      ANCHOR[r * 3 + 1] = HEMI.y + y * (y < 0 ? HEMI.ryb : HEMI.ry) * 0.8;
      ANCHOR[r * 3 + 2] = HEMI.z + dz * HEMI.rz * 0.8;
    });
    tests.forEach((r, k) => {
      regionHome[r] = 0;
      const t = tests.length === 1 ? 0.5 : k / (tests.length - 1);
      ANCHOR[r * 3] = CERE.x + (t - 0.5) * CERE.rx * 1.3;
      ANCHOR[r * 3 + 1] = CERE.y;
      ANCHOR[r * 3 + 2] = CERE.z;
    });
  }

  const POS = new Float32Array(N * 3);
  const maxRegion = Math.max(1, ...REGION_SIZE);
  for (let i = 0; i < N; i++) {
    const r = REGION[i];
    HOME[i] = TEST[i] ? 0 : (regionHome[r] === 0 ? (i % 2 ? 1 : -1) : regionHome[r]);
    const spread = (HOME[i] === 0 ? 0.07 : 0.09) + 0.16 * Math.sqrt(REGION_SIZE[r] / maxRegion);
    let ax = ANCHOR[r * 3], ay = ANCHOR[r * 3 + 1], az = ANCHOR[r * 3 + 2];
    if (TEST[i] && regionHome[r] !== 0) { ax = CERE.x + (rand() - 0.5) * 0.5; ay = CERE.y; az = CERE.z; }
    if (!TEST[i] && regionHome[r] === 0) { ax = HOME[i] * 0.5; ay = 0.2; az = 0; }
    POS[i * 3] = ax + gauss() * spread; POS[i * 3 + 1] = ay + gauss() * spread; POS[i * 3 + 2] = az + gauss() * spread;
    constrain(POS, i * 3, HOME[i]);
  }
  const HOME_ANCHOR = new Float32Array(N * 3);
  for (let i = 0; i < N; i++) HOME_ANCHOR.set(POS.subarray(i * 3, i * 3 + 3), i * 3);

  // A position-based force layout: fibres pull, neighbours push apart, every particle stays
  // near its region and inside its part of the brain. It runs a few steps per frame, so the
  // brain is seen settling into shape rather than appearing after a pause.
  const SIM_STEPS = 150;
  let simStep = 0;
  const SPRING_W = new Float32Array(N);
  for (let i = 0; i < N; i++) SPRING_W[i] = 1 / Math.sqrt(1 + DEG[i]);
  function simulate(steps) {
    const cell = 0.055, inv = 1 / cell;
    for (let k = 0; k < steps && simStep < SIM_STEPS; k++, simStep++) {
      const heat = 1 - simStep / SIM_STEPS;
      for (let e = 0; e < E; e++) {
        const a = ESRC[e] * 3, b = EDST[e] * 3;
        if (HOME[ESRC[e]] !== HOME[EDST[e]]) continue;
        const dx = POS[b] - POS[a], dy = POS[b + 1] - POS[a + 1], dz = POS[b + 2] - POS[a + 2];
        const d = Math.sqrt(dx * dx + dy * dy + dz * dz) + 1e-6;
        const f = (d - 0.06) / d * 0.09 * heat * (REGION[ESRC[e]] === REGION[EDST[e]] ? 1 : 0.25);
        const wa = SPRING_W[ESRC[e]] * f, wb = SPRING_W[EDST[e]] * f;
        POS[a] += dx * wa; POS[a + 1] += dy * wa; POS[a + 2] += dz * wa;
        POS[b] -= dx * wb; POS[b + 1] -= dy * wb; POS[b + 2] -= dz * wb;
      }
      const grid = new Map();
      for (let i = 0; i < N; i++) {
        const o = i * 3;
        POS[o] += (HOME_ANCHOR[o] - POS[o]) * 0.035 * heat;
        POS[o + 1] += (HOME_ANCHOR[o + 1] - POS[o + 1]) * 0.035 * heat;
        POS[o + 2] += (HOME_ANCHOR[o + 2] - POS[o + 2]) * 0.035 * heat;
        const key = ((Math.floor(POS[o] * inv) + 64) * 128 + (Math.floor(POS[o + 1] * inv) + 64)) * 128 + (Math.floor(POS[o + 2] * inv) + 64);
        const bucket = grid.get(key);
        if (bucket) bucket.push(i); else grid.set(key, [i]);
      }
      for (let i = 0; i < N; i++) {
        const o = i * 3;
        const cx = Math.floor(POS[o] * inv), cy = Math.floor(POS[o + 1] * inv), cz = Math.floor(POS[o + 2] * inv);
        for (let gx = -1; gx <= 1; gx++) for (let gy = -1; gy <= 1; gy++) for (let gz = -1; gz <= 1; gz++) {
          const bucket = grid.get(((cx + gx + 64) * 128 + (cy + gy + 64)) * 128 + (cz + gz + 64));
          if (!bucket) continue;
          for (const j of bucket) {
            if (j <= i) continue;
            const p = j * 3;
            const dx = POS[p] - POS[o], dy = POS[p + 1] - POS[o + 1], dz = POS[p + 2] - POS[o + 2];
            const d2 = dx * dx + dy * dy + dz * dz;
            if (d2 >= cell * cell) continue;
            const d = Math.sqrt(d2) + 1e-6, push = (cell - d) / d * 0.25;
            POS[o] -= dx * push; POS[o + 1] -= dy * push; POS[o + 2] -= dz * push;
            POS[p] += dx * push; POS[p + 1] += dy * push; POS[p + 2] += dz * push;
          }
        }
      }
      for (let i = 0; i < N; i++) constrain(POS, i * 3, HOME[i]);
    }
    placeMemories();
  }

  // A memory floats just outside the cortex above the code it describes; one about code that is
  // not drawn joins a ring of loose thoughts over the crown.
  function placeMemories() {
    let loose = 0;
    const looseTotal = MEM.filter((m) => m.anchors.length === 0).length;
    MEM.forEach((m) => {
      if (m.anchors.length) {
        let x = 0, y = 0, z = 0;
        for (const a of m.anchors) { x += POS[a * 3]; y += POS[a * 3 + 1]; z += POS[a * 3 + 2]; }
        x /= m.anchors.length; y /= m.anchors.length; z /= m.anchors.length;
        const len = Math.hypot(x, y - 0.0, z) || 1;
        m.pos[0] = x + (x / len) * 0.13; m.pos[1] = y + (y / len) * 0.13 + 0.04; m.pos[2] = z + (z / len) * 0.13;
      } else {
        const t = (loose++ / Math.max(1, looseTotal)) * Math.PI * 2;
        m.pos[0] = Math.cos(t) * 0.55; m.pos[1] = 0.88; m.pos[2] = Math.sin(t) * 0.75;
      }
    });
  }

  // The cortex: points scattered over the surface, brighter on the folds, so the brain has its
  // outline even when the repository is small.
  function folds(x, y, z) {
    return (Math.sin(9 * z + 2.2 * Math.sin(6 * y)) + Math.sin(8.5 * y + 2.0 * Math.sin(7 * x + 1.3)) + 0.7 * Math.sin(11 * x + 3 * z + 1.7 * Math.sin(5 * y))) / 2.7;
  }
  function buildCortex() {
    const out = [];
    const r2 = rng(7);
    const unit = () => { const u = r2() * 2 - 1, t = r2() * Math.PI * 2, s = Math.sqrt(1 - u * u); return [s * Math.cos(t), u, s * Math.sin(t)]; };
    const COUNT = 11000;
    for (let n = 0; n < COUNT; n++) {
      const pick = r2();
      let x, y, z, bright;
      if (pick < 0.84) {
        const h = r2() < 0.5 ? -1 : 1;
        const d = unit();
        const ry = d[1] < 0 ? HEMI.ryb : HEMI.ry;
        x = h * HEMI.x + d[0] * HEMI.rx; y = HEMI.y + d[1] * ry; z = HEMI.z + d[2] * HEMI.rz;
        if (h * x < FISSURE * 0.6) continue;
        const g = folds(x, y, z);
        const sulcus = Math.abs(g) < 0.14;
        const k = sulcus ? 0.955 : 1.0 + 0.012 * g;
        x = h * HEMI.x + (x - h * HEMI.x) * k; y = HEMI.y + (y - HEMI.y) * k; z = HEMI.z + (z - HEMI.z) * k;
        bright = sulcus ? 0.18 : 0.30 + 0.45 * Math.abs(g);
      } else if (pick < 0.97) {
        const d = unit();
        x = CERE.x + d[0] * CERE.rx; y = CERE.y + d[1] * CERE.ry; z = CERE.z + d[2] * CERE.rz;
        const stripes = Math.abs(Math.sin(y * 70 + x * 4));
        bright = 0.18 + 0.4 * stripes;
      } else {
        const t = r2(), a = r2() * Math.PI * 2;
        x = Math.cos(a) * 0.085; z = -0.22 + Math.sin(a) * 0.085 - t * 0.12; y = -0.30 - t * 0.55;
        bright = 0.25;
      }
      out.push(x, y, z, bright);
    }
    return out;
  }

  // ---------------------------------------------------------------- WebGL
  const canvas = $('scene');
  const gl = canvas.getContext('webgl', { antialias: true, alpha: false, preserveDrawingBuffer: false })
    || canvas.getContext('experimental-webgl');
  function showMessage(html) { const m = $('message'); m.innerHTML = html; m.classList.add('open'); }
  if (!gl) { showMessage(S.noGl); return; }

  function shader(type, src) { const s = gl.createShader(type); gl.shaderSource(s, src); gl.compileShader(s); return s; }
  function program(vs, fs) {
    const p = gl.createProgram();
    gl.attachShader(p, shader(gl.VERTEX_SHADER, vs)); gl.attachShader(p, shader(gl.FRAGMENT_SHADER, fs));
    gl.linkProgram(p);
    if (!gl.getProgramParameter(p, gl.LINK_STATUS)) throw new Error(gl.getProgramInfoLog(p) || 'link');
    return p;
  }
  const POINT_VS = `
    attribute vec3 aPos; attribute vec3 aColor; attribute float aSize; attribute float aAlpha; attribute float aShape;
    uniform mat4 uMVP; uniform float uScale; uniform float uTime; uniform vec2 uFog;
    varying vec3 vColor; varying float vAlpha; varying float vShape;
    void main() {
      vec4 p = uMVP * vec4(aPos, 1.0);
      gl_Position = p;
      float size = aSize * uScale / max(p.w, 0.05);
      gl_PointSize = clamp(size, 1.6, 110.0);
      float twinkle = aShape > 1.5 ? 0.7 + 0.3 * sin(uTime * 1.3 + aPos.x * 37.0 + aPos.y * 23.0 + aPos.z * 17.0) : 1.0;
      float fog = clamp((p.w - uFog.x) / (uFog.y - uFog.x), 0.0, 1.0);
      vAlpha = aAlpha * twinkle * (1.0 - 0.6 * fog) * clamp(size / 1.6, 0.25, 1.0);
      vColor = aColor; vShape = aShape;
    }`;
  const POINT_FS = `
    precision mediump float;
    varying vec3 vColor; varying float vAlpha; varying float vShape;
    void main() {
      vec2 c = gl_PointCoord * 2.0 - 1.0;
      float d = dot(c, c);
      if (d > 1.0) discard;
      float a;
      if (vShape < 0.5) {
        a = exp(-d * 5.5) * 0.55 + smoothstep(0.16, 0.0, d) * 1.0;
      } else if (vShape < 1.5) {
        float r = sqrt(d);
        a = smoothstep(0.13, 0.0, abs(r - 0.74)) + smoothstep(0.32, 0.0, r) * 0.95 + exp(-d * 3.0) * 0.25;
      } else {
        a = exp(-d * 6.0);
      }
      gl_FragColor = vec4(vColor * a * vAlpha, 1.0);
    }`;
  const LINE_VS = `
    attribute vec3 aPos; attribute vec3 aColor; attribute float aAlpha;
    uniform mat4 uMVP; uniform vec2 uFog; uniform float uDim;
    varying vec3 vColor; varying float vAlpha;
    void main() {
      vec4 p = uMVP * vec4(aPos, 1.0);
      gl_Position = p;
      float fog = clamp((p.w - uFog.x) / (uFog.y - uFog.x), 0.0, 1.0);
      vAlpha = aAlpha * uDim * (1.0 - 0.55 * fog);
      vColor = aColor;
    }`;
  const LINE_FS = `
    precision mediump float;
    varying vec3 vColor; varying float vAlpha;
    void main() { gl_FragColor = vec4(vColor * vAlpha, 1.0); }`;

  let pointProg, lineProg;
  try { pointProg = program(POINT_VS, POINT_FS); lineProg = program(LINE_VS, LINE_FS); } catch (_) { showMessage(S.noGl); return; }
  const PA = ['aPos', 'aColor', 'aSize', 'aAlpha', 'aShape'].map((n) => gl.getAttribLocation(pointProg, n));
  const LA = ['aPos', 'aColor', 'aAlpha'].map((n) => gl.getAttribLocation(lineProg, n));
  const PU = {}, LU = {};
  ['uMVP', 'uScale', 'uTime', 'uFog'].forEach((n) => { PU[n] = gl.getUniformLocation(pointProg, n); });
  ['uMVP', 'uFog', 'uDim'].forEach((n) => { LU[n] = gl.getUniformLocation(lineProg, n); });

  const POINT_STRIDE = 9, LINE_STRIDE = 7;
  function makeBuffer() { return { buf: gl.createBuffer(), count: 0 }; }
  function upload(b, data, stride) { gl.bindBuffer(gl.ARRAY_BUFFER, b.buf); gl.bufferData(gl.ARRAY_BUFFER, data, gl.DYNAMIC_DRAW); b.count = data.length / stride; }
  function drawPoints(b) {
    if (!b.count) return;
    gl.bindBuffer(gl.ARRAY_BUFFER, b.buf);
    const sizes = [3, 3, 1, 1, 1]; let off = 0;
    PA.forEach((loc, k) => { if (loc >= 0) { gl.enableVertexAttribArray(loc); gl.vertexAttribPointer(loc, sizes[k], gl.FLOAT, false, POINT_STRIDE * 4, off * 4); } off += sizes[k]; });
    gl.drawArrays(gl.POINTS, 0, b.count);
  }
  function drawLines(b) {
    if (!b.count) return;
    gl.bindBuffer(gl.ARRAY_BUFFER, b.buf);
    const sizes = [3, 3, 1]; let off = 0;
    LA.forEach((loc, k) => { if (loc >= 0) { gl.enableVertexAttribArray(loc); gl.vertexAttribPointer(loc, sizes[k], gl.FLOAT, false, LINE_STRIDE * 4, off * 4); } off += sizes[k]; });
    gl.drawArrays(gl.LINES, 0, b.count);
  }

  const B = { cortex: makeBuffer(), nodes: makeBuffer(), edges: makeBuffer(), focus: makeBuffer(), mem: makeBuffer(), memLines: makeBuffer(), pulses: makeBuffer(), halo: makeBuffer() };

  const cortexData = (() => {
    const src = buildCortex();
    const out = new Float32Array((src.length / 4) * POINT_STRIDE);
    for (let k = 0, o = 0; k < src.length; k += 4, o += POINT_STRIDE) {
      out[o] = src[k]; out[o + 1] = src[k + 1]; out[o + 2] = src[k + 2];
      out[o + 3] = 0.55; out[o + 4] = 0.66; out[o + 5] = 1.0;
      out[o + 6] = 0.012; out[o + 7] = src[k + 3]; out[o + 8] = 2;
    }
    return out;
  })();
  upload(B.cortex, cortexData, POINT_STRIDE);

  // ---------------------------------------------------------------- state
  const state = {
    selected: -1, selectedMem: -1, hovered: -1, hoveredMem: -1, region: -1,
    show: { edges: true, signals: true, memories: true, cortex: true, labels: true, rotate: true },
  };
  // Which nodes are lit: the selection and its neighbours, or a whole region, or everything.
  const LIT = new Float32Array(N);
  function computeLit() {
    if (state.selected >= 0) {
      LIT.fill(0.12);
      const s = state.selected;
      LIT[s] = 1;
      for (const e of OUT[s]) LIT[EDST[e]] = 1;
      for (const e of IN[s]) LIT[ESRC[e]] = 1;
    } else if (state.selectedMem >= 0) {
      LIT.fill(0.12);
      for (const a of MEM[state.selectedMem].anchors) LIT[a] = 1;
    } else if (state.region >= 0) {
      for (let i = 0; i < N; i++) LIT[i] = REGION[i] === state.region ? 1 : 0.08;
    } else {
      LIT.fill(1);
    }
  }
  computeLit();
  const dimmed = () => state.selected >= 0 || state.selectedMem >= 0 || state.region >= 0;

  // Light adds up: thousands of particles drawn additively burn to white, so each one is dimmer
  // the more of them there are.
  const EXPOSURE = Math.min(1, Math.sqrt(1200 / Math.max(1, N)) * 0.9 + 0.12);
  function nodeSize(i) { return 0.016 + 0.009 * Math.log2(1 + DEG[i]) + (BIG_KINDS.has(kindName(i)) ? 0.006 : 0); }
  const nodeData = new Float32Array(N * POINT_STRIDE);
  function writeNodes() {
    for (let i = 0, o = 0; i < N; i++, o += POINT_STRIDE) {
      const c = REGION_RGB[REGION[i]];
      nodeData[o] = POS[i * 3]; nodeData[o + 1] = POS[i * 3 + 1]; nodeData[o + 2] = POS[i * 3 + 2];
      nodeData[o + 3] = c[0]; nodeData[o + 4] = c[1]; nodeData[o + 5] = c[2];
      nodeData[o + 6] = nodeSize(i) * (i === state.selected ? 1.6 : 1);
      nodeData[o + 7] = (0.45 + 0.55 * Math.min(1, DEG[i] / 12)) * EXPOSURE * (LIT[i] >= 1 && dimmed() ? 1.6 : LIT[i]);
      nodeData[o + 8] = 0;
    }
    upload(B.nodes, nodeData, POINT_STRIDE);
  }

  // A fibre is a curve that dips towards the centre of the brain, the way white matter runs
  // under the cortex, and fades from where it leaves to where it arrives so its direction shows.
  const SEG = 5;
  function curvePoint(a, b, t, out) {
    const mx = (POS[a * 3] + POS[b * 3]) * 0.5, my = (POS[a * 3 + 1] + POS[b * 3 + 1]) * 0.5, mz = (POS[a * 3 + 2] + POS[b * 3 + 2]) * 0.5;
    const cx = mx * 0.55, cy = my * 0.55 - 0.05, cz = mz * 0.55;
    const u = 1 - t;
    out[0] = u * u * POS[a * 3] + 2 * u * t * cx + t * t * POS[b * 3];
    out[1] = u * u * POS[a * 3 + 1] + 2 * u * t * cy + t * t * POS[b * 3 + 1];
    out[2] = u * u * POS[a * 3 + 2] + 2 * u * t * cz + t * t * POS[b * 3 + 2];
    return out;
  }
  const MAX_DRAWN_EDGES = 60000;
  const EDRAWN = Math.min(E, MAX_DRAWN_EDGES);
  const edgeData = new Float32Array(EDRAWN * SEG * 2 * LINE_STRIDE);
  const baseEdgeAlpha = Math.min(0.16, 0.045 * Math.sqrt(2000 / Math.max(1, EDRAWN)) + 0.01);
  const tmpA = [0, 0, 0], tmpB = [0, 0, 0];
  function writeCurve(arr, o, a, b, color, alpha, endFade) {
    for (let s = 0; s < SEG; s++) {
      const t0 = s / SEG, t1 = (s + 1) / SEG;
      curvePoint(a, b, t0, tmpA); curvePoint(a, b, t1, tmpB);
      arr[o] = tmpA[0]; arr[o + 1] = tmpA[1]; arr[o + 2] = tmpA[2];
      arr[o + 3] = color[0]; arr[o + 4] = color[1]; arr[o + 5] = color[2]; arr[o + 6] = alpha * (1 - endFade * t0);
      o += LINE_STRIDE;
      arr[o] = tmpB[0]; arr[o + 1] = tmpB[1]; arr[o + 2] = tmpB[2];
      arr[o + 3] = color[0]; arr[o + 4] = color[1]; arr[o + 5] = color[2]; arr[o + 6] = alpha * (1 - endFade * t1);
      o += LINE_STRIDE;
    }
    return o;
  }
  function writeEdges() {
    let o = 0;
    for (let e = 0; e < EDRAWN; e++) {
      const a = ESRC[e], b = EDST[e];
      const lit = Math.min(LIT[a], LIT[b]);
      const alpha = baseEdgeAlpha * (ECONF[e] === 0 ? 0.45 : 1) * (dimmed() ? (lit >= 1 ? 2.2 : 0.35) : 1);
      o = writeCurve(edgeData, o, a, b, REGION_RGB[REGION[a]], alpha, 0.75);
    }
    upload(B.edges, edgeData.subarray(0, o), LINE_STRIDE);
  }
  function writeFocus() {
    const s = state.selected;
    if (s < 0) { B.focus.count = 0; return; }
    const list = OUT[s].concat(IN[s]);
    const arr = new Float32Array(list.length * SEG * 2 * LINE_STRIDE);
    let o = 0;
    for (const e of list) o = writeCurve(arr, o, ESRC[e], EDST[e], ESRC[e] === s ? CALLS_RGB : CALLED_RGB, 0.75, 0.55);
    upload(B.focus, arr.subarray(0, o), LINE_STRIDE);
  }
  function writeMemories() {
    const pts = new Float32Array(MEM.length * POINT_STRIDE);
    const lines = [];
    MEM.forEach((m, k) => {
      const o = k * POINT_STRIDE, c = m.stale ? STALE_RGB : MEM_RGB;
      pts.set([m.pos[0], m.pos[1], m.pos[2], c[0], c[1], c[2], k === state.selectedMem ? 0.11 : 0.075, 1, 1], o);
      for (const a of m.anchors) lines.push(m.pos[0], m.pos[1], m.pos[2], c[0], c[1], c[2], 0.5, POS[a * 3], POS[a * 3 + 1], POS[a * 3 + 2], c[0], c[1], c[2], 0.12);
    });
    upload(B.mem, pts, POINT_STRIDE);
    upload(B.memLines, new Float32Array(lines), LINE_STRIDE);
  }

  // Signals: pulses travelling along fibres from caller to callee. With a selection they run
  // only on its own fibres, so what it calls and what calls it can be watched.
  const pulses = [];
  const pulseData = new Float32Array(400 * POINT_STRIDE);
  function pickPulseEdge() {
    const s = state.selected;
    if (s >= 0) { const list = OUT[s].concat(IN[s]); return list.length ? list[Math.floor(Math.random() * list.length)] : -1; }
    if (state.region >= 0) {
      for (let tries = 0; tries < 12; tries++) { const e = Math.floor(Math.random() * EDRAWN); if (REGION[ESRC[e]] === state.region) return e; }
      return -1;
    }
    return EDRAWN ? Math.floor(Math.random() * EDRAWN) : -1;
  }
  function resetPulses() {
    pulses.length = 0;
    const target = state.selected >= 0 ? Math.min(160, (OUT[state.selected].length + IN[state.selected].length) * 4) : Math.min(260, EDRAWN);
    for (let k = 0; k < target; k++) pulses.push({ e: pickPulseEdge(), t: Math.random(), v: 0.25 + Math.random() * 0.35 });
  }
  function writePulses(dt) {
    let o = 0;
    for (const p of pulses) {
      p.t += dt * p.v;
      if (p.t >= 1 || p.t < 0 || p.e < 0) { p.e = pickPulseEdge(); p.t = 0; }
      if (p.e < 0 || o >= pulseData.length) continue;
      const a = ESRC[p.e], b = EDST[p.e];
      curvePoint(a, b, p.t, tmpA);
      const c = state.selected >= 0 ? (a === state.selected ? CALLS_RGB : CALLED_RGB) : REGION_RGB[REGION[a]];
      const fade = Math.sin(Math.PI * p.t);
      pulseData.set([tmpA[0], tmpA[1], tmpA[2], 0.6 + c[0] * 0.4, 0.6 + c[1] * 0.4, 0.6 + c[2] * 0.4, 0.028, fade, 0], o);
      o += POINT_STRIDE;
    }
    upload(B.pulses, pulseData.subarray(0, o), POINT_STRIDE);
  }

  // ---------------------------------------------------------------- camera
  const HOME_DIST = 2.75;
  const cam = { theta: -1.05, phi: 0.3, dist: HOME_DIST, tx: 0, ty: -0.08, tz: 0 };
  const goal = { ...cam };
  let MVP = new Float32Array(16), W = 1, H = 1, DPR = 1, SCALE = 1;
  const FOV = 50 * Math.PI / 180;
  function mat4Perspective(fovy, aspect, near, far) {
    const f = 1 / Math.tan(fovy / 2), nf = 1 / (near - far);
    return new Float32Array([f / aspect, 0, 0, 0, 0, f, 0, 0, 0, 0, (far + near) * nf, -1, 0, 0, 2 * far * near * nf, 0]);
  }
  function mat4LookAt(e, t, u) {
    let zx = e[0] - t[0], zy = e[1] - t[1], zz = e[2] - t[2];
    let l = Math.hypot(zx, zy, zz) || 1; zx /= l; zy /= l; zz /= l;
    let xx = u[1] * zz - u[2] * zy, xy = u[2] * zx - u[0] * zz, xz = u[0] * zy - u[1] * zx;
    l = Math.hypot(xx, xy, xz) || 1; xx /= l; xy /= l; xz /= l;
    const yx = zy * xz - zz * xy, yy = zz * xx - zx * xz, yz = zx * xy - zy * xx;
    return new Float32Array([xx, yx, zx, 0, xy, yy, zy, 0, xz, yz, zz, 0,
      -(xx * e[0] + xy * e[1] + xz * e[2]), -(yx * e[0] + yy * e[1] + yz * e[2]), -(zx * e[0] + zy * e[1] + zz * e[2]), 1]);
  }
  function mat4Mul(a, b) {
    const o = new Float32Array(16);
    for (let c = 0; c < 4; c++) for (let r = 0; r < 4; r++) {
      o[c * 4 + r] = a[r] * b[c * 4] + a[4 + r] * b[c * 4 + 1] + a[8 + r] * b[c * 4 + 2] + a[12 + r] * b[c * 4 + 3];
    }
    return o;
  }
  function updateCamera() {
    const k = 0.12;
    for (const key of ['theta', 'phi', 'dist', 'tx', 'ty', 'tz']) cam[key] += (goal[key] - cam[key]) * k;
    const cp = Math.cos(cam.phi);
    const eye = [cam.tx + cam.dist * cp * Math.sin(cam.theta), cam.ty + cam.dist * Math.sin(cam.phi), cam.tz + cam.dist * cp * Math.cos(cam.theta)];
    const proj = mat4Perspective(FOV, W / H, 0.02, 40);
    MVP = mat4Mul(proj, mat4LookAt(eye, [cam.tx, cam.ty, cam.tz], [0, 1, 0]));
  }
  function project(x, y, z) {
    const m = MVP;
    const cx = m[0] * x + m[4] * y + m[8] * z + m[12], cy = m[1] * x + m[5] * y + m[9] * z + m[13], w = m[3] * x + m[7] * y + m[11] * z + m[15];
    if (w <= 0.01) return null;
    return [(cx / w * 0.5 + 0.5) * W, (0.5 - cy / w * 0.5) * H, w];
  }
  function flyTo(x, y, z, dist) { goal.tx = x; goal.ty = y; goal.tz = z; goal.dist = dist; }

  function resize() {
    DPR = Math.min(window.devicePixelRatio || 1, 2);
    W = window.innerWidth; H = window.innerHeight;
    canvas.width = Math.round(W * DPR); canvas.height = Math.round(H * DPR);
    gl.viewport(0, 0, canvas.width, canvas.height);
    SCALE = (canvas.height / 2) / Math.tan(FOV / 2);
  }
  window.addEventListener('resize', resize);
  resize();

  // ---------------------------------------------------------------- picking
  function pick(mx, my) {
    let best = -1, bestMem = -1, bestD = Infinity;
    if (state.show.memories) {
      MEM.forEach((m, k) => {
        const p = project(m.pos[0], m.pos[1], m.pos[2]);
        if (!p) return;
        const d = Math.hypot(p[0] - mx, p[1] - my), r = Math.max(10, 0.075 * SCALE / p[2] / DPR * 0.6);
        if (d < r && d < bestD) { bestD = d; bestMem = k; }
      });
    }
    for (let i = 0; i < N; i++) {
      if (LIT[i] < 0.5 && dimmed()) continue;
      const p = project(POS[i * 3], POS[i * 3 + 1], POS[i * 3 + 2]);
      if (!p) continue;
      const d = Math.hypot(p[0] - mx, p[1] - my), r = Math.max(7, nodeSize(i) * SCALE / p[2] / DPR * 0.6);
      if (d < r && d - (bestMem >= 0 ? 4 : 0) < bestD) { bestD = d; best = i; bestMem = -1; }
    }
    return { node: best, mem: bestMem };
  }

  // ---------------------------------------------------------------- labels
  const labelLayer = $('labels');
  const labelPool = [];
  function labelEl(k) {
    while (labelPool.length <= k) { const d = document.createElement('div'); d.className = 'label'; labelLayer.appendChild(d); labelPool.push(d); }
    return labelPool[k];
  }
  const hubs = Array.from({ length: N }, (_, i) => i).sort((a, b) => DEG[b] - DEG[a]).slice(0, 12);
  function drawLabels() {
    const want = [];
    if (state.show.labels) {
      if (state.selected >= 0) {
        want.push([state.selected, 'sel']);
        const around = OUT[state.selected].map((e) => EDST[e]).concat(IN[state.selected].map((e) => ESRC[e]));
        [...new Set(around)].sort((a, b) => DEG[b] - DEG[a]).slice(0, 16).forEach((i) => want.push([i, '']));
      } else if (state.selectedMem >= 0) {
        MEM[state.selectedMem].anchors.slice(0, 16).forEach((i) => want.push([i, '']));
      } else if (state.region >= 0) {
        Array.from({ length: N }, (_, i) => i).filter((i) => REGION[i] === state.region).sort((a, b) => DEG[b] - DEG[a]).slice(0, 14).forEach((i) => want.push([i, 'hub']));
      } else {
        hubs.forEach((i) => want.push([i, 'hub']));
      }
    }
    if (state.hovered >= 0 && !want.some((w) => w[0] === state.hovered)) want.push([state.hovered, 'sel']);
    let k = 0;
    const placed = [];
    for (const [i, cls] of want) {
      const p = project(POS[i * 3], POS[i * 3 + 1], POS[i * 3 + 2]);
      if (!p || p[0] < -50 || p[0] > W + 50 || p[1] < -20 || p[1] > H + 20) continue;
      // Labels that would overlap one already placed are skipped, the selection never.
      const box = [p[0] + 9, p[1] - 9, p[0] + 23 + NAME[i].length * 6.7, p[1] + 11];
      if (cls !== 'sel' && placed.some((q) => box[0] < q[2] && q[0] < box[2] && box[1] < q[3] && q[1] < box[3])) continue;
      placed.push(box);
      const d = labelEl(k++);
      d.className = 'label ' + cls;
      if (d.textContent !== NAME[i]) d.textContent = NAME[i];
      d.style.transform = `translate(${Math.round(p[0] + 9)}px, ${Math.round(p[1] - 9)}px)`;
      d.style.opacity = String(Math.max(0.35, Math.min(1, 1.6 - (p[2] - cam.dist) * 0.9)));
    }
    if (state.hoveredMem >= 0) {
      const m = MEM[state.hoveredMem], p = project(m.pos[0], m.pos[1], m.pos[2]);
      if (p) {
        const d = labelEl(k++);
        d.className = 'label mem';
        const text = m.text.length > 60 ? m.text.slice(0, 59) + '…' : m.text;
        if (d.textContent !== text) d.textContent = text;
        d.style.transform = `translate(${Math.round(p[0] + 12)}px, ${Math.round(p[1] - 10)}px)`;
        d.style.opacity = '1';
      }
    }
    for (let j = k; j < labelPool.length; j++) labelPool[j].style.opacity = '0';
  }

  // ---------------------------------------------------------------- the panel
  const panel = $('panel');
  function el(tag, cls, text) { const e = document.createElement(tag); if (cls) e.className = cls; if (text != null) e.textContent = text; return e; }
  function dot(rgb) { const d = el('span', 'dot'); d.style.background = rgbCss(rgb); d.style.boxShadow = `0 0 8px ${rgbCss(rgb)}`; return d; }
  function chip(text, rgb, cls) { const c = el('span', 'chip' + (cls ? ' ' + cls : '')); if (rgb) c.appendChild(dot(rgb)); c.appendChild(document.createTextNode(text)); return c; }
  function toast(text) { const t = $('toast'); t.textContent = text; t.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => t.classList.remove('show'), 1600); }
  function copy(text) {
    const done = () => toast(S.copied);
    const fallback = () => {
      const ta = el('textarea'); ta.value = text; ta.style.position = 'fixed'; ta.style.opacity = '0'; document.body.appendChild(ta); ta.select();
      try { document.execCommand('copy') ? done() : toast(S.copyFail); } catch (_) { toast(S.copyFail); }
      ta.remove();
    };
    if (navigator.clipboard && navigator.clipboard.writeText) navigator.clipboard.writeText(text).then(done, fallback); else fallback();
  }
  function linkList(items, color) {
    const ul = el('ul', 'links');
    const LIMIT = 40;
    items.slice(0, LIMIT).forEach((i) => {
      const li = el('li'), b = el('button');
      b.appendChild(dot(color ? color : REGION_RGB[REGION[i]]));
      b.appendChild(el('span', 'nm', QUAL[i]));
      const parts = pathOf(i).split('/');
      b.appendChild(el('span', 'pt', parts.slice(-2).join('/') + ':' + LINE[i]));
      b.title = `${QUAL[i]} · ${pathOf(i)}:${LINE[i]}`;
      b.addEventListener('click', () => select(i, true));
      li.appendChild(b); ul.appendChild(li);
    });
    if (items.length > LIMIT) ul.appendChild(el('li', 'more', S.more(items.length - LIMIT)));
    return ul;
  }
  function heading(text, swatch) { const h = el('h4'); if (swatch) { const s = el('span', 'sw'); s.style.background = rgbCss(swatch); h.appendChild(s); } h.appendChild(document.createTextNode(text)); return h; }
  function memoryCard(k) {
    const m = MEM[k], card = el('div', 'memcard' + (m.stale ? ' stale' : ''));
    const chips = el('div', 'chips');
    chips.appendChild(chip(m.kind, m.stale ? STALE_RGB : MEM_RGB, 'mem'));
    if (m.stale) chips.appendChild(chip(S.stale, null, 'stale'));
    if (m.by) chips.appendChild(chip(m.by));
    card.appendChild(chips);
    card.appendChild(el('p', '', m.text));
    return card;
  }
  function uniqueNeighbors(list, end) { return [...new Set(list.map((e) => end[e]))].sort((a, b) => DEG[b] - DEG[a]); }
  function contextFor(i) {
    const callers = uniqueNeighbors(IN[i], ESRC), callees = uniqueNeighbors(OUT[i], EDST);
    const lines = [`# ${QUAL[i]} (${kindName(i)})`, `${pathOf(i)}:${LINE[i]}`];
    if (SIG[i]) lines.push('', SIG[i]);
    if (DOC[i]) lines.push('', DOC[i]);
    const names = (xs) => xs.slice(0, 15).map((j) => `${QUAL[j]} (${pathOf(j)}:${LINE[j]})`).join(', ') + (xs.length > 15 ? ', …' : '');
    if (callers.length) lines.push('', `${S.ctxCalledBy} (${callers.length}): ${names(callers)}`);
    if (callees.length) lines.push(`${S.ctxCalls} (${callees.length}): ${names(callees)}`);
    const mems = MEM_OF[i].map((k) => MEM[k]);
    if (mems.length) { lines.push('', `${S.mems}:`); mems.forEach((m) => lines.push(`- [${m.kind}${m.stale ? ', ' + S.stale : ''}] ${m.text}`)); }
    lines.push('', `${S.ctxNext}: pn-ultramemory expand ${ID[i]} · pn-ultramemory impact ${ID[i]}`);
    return lines.join('\n');
  }
  function renderNode(i) {
    panel.replaceChildren();
    const close = el('button', 'close', '×'); close.setAttribute('aria-label', 'close'); close.addEventListener('click', clearSelection); panel.appendChild(close);
    const chips = el('div', 'chips');
    chips.appendChild(chip(kindName(i)));
    chips.appendChild(chip(DATA.regions[REGION[i]] || '.', REGION_RGB[REGION[i]]));
    if (TEST[i]) chips.appendChild(chip(S.test));
    if (MEM_OF[i].length) chips.appendChild(chip(S.memCount(MEM_OF[i].length), MEM_RGB, 'mem'));
    panel.appendChild(chips);
    panel.appendChild(el('h2', '', NAME[i]));
    if (QUAL[i] !== NAME[i]) panel.appendChild(el('div', 'qual', QUAL[i]));
    const loc = el('button', 'loc', `${pathOf(i)}:${LINE[i]}`); loc.title = S.copyLoc; loc.addEventListener('click', () => copy(`${pathOf(i)}:${LINE[i]}`)); panel.appendChild(loc);
    const callers = uniqueNeighbors(IN[i], ESRC), callees = uniqueNeighbors(OUT[i], EDST);
    const deg = el('div', 'degree');
    const d1 = el('span'); d1.appendChild(el('b', '', fmt(callers.length))); d1.appendChild(document.createTextNode(' ' + S.calledBy.toLowerCase()));
    const d2 = el('span'); d2.appendChild(el('b', '', fmt(callees.length))); d2.appendChild(document.createTextNode(' ' + S.calls.toLowerCase()));
    deg.append(d1, d2); panel.appendChild(deg);
    if (SIG[i]) { panel.appendChild(heading(S.sig)); panel.appendChild(el('pre', '', SIG[i])); }
    if (DOC[i]) panel.appendChild(el('p', 'doc', DOC[i]));
    if (MEM_OF[i].length) { panel.appendChild(heading(S.mems, MEM_RGB)); MEM_OF[i].forEach((k) => panel.appendChild(memoryCard(k))); }
    if (callers.length) { panel.appendChild(heading(`${S.calledBy} · ${fmt(callers.length)}`, CALLED_RGB)); panel.appendChild(linkList(callers)); }
    if (callees.length) { panel.appendChild(heading(`${S.calls} · ${fmt(callees.length)}`, CALLS_RGB)); panel.appendChild(linkList(callees)); }
    const actions = el('div', 'actions');
    const b1 = el('button', 'btn', S.copyCtx); b1.addEventListener('click', () => copy(contextFor(i)));
    const b2 = el('button', 'btn ghost', S.focus); b2.addEventListener('click', () => flyTo(POS[i * 3], POS[i * 3 + 1], POS[i * 3 + 2], 1.25));
    actions.append(b1, b2); panel.appendChild(actions);
    panel.classList.add('open');
    panel.scrollTop = 0;
  }
  function renderMemory(k) {
    const m = MEM[k];
    panel.replaceChildren();
    const close = el('button', 'close', '×'); close.setAttribute('aria-label', 'close'); close.addEventListener('click', clearSelection); panel.appendChild(close);
    panel.appendChild(el('div', 'chips')).appendChild(chip(S.memory + ' #' + m.id, m.stale ? STALE_RGB : MEM_RGB, 'mem'));
    panel.appendChild(memoryCard(k));
    if (m.stale) panel.appendChild(el('p', 'doc', S.staleWhy));
    panel.appendChild(heading(S.anchored));
    if (m.anchors.length) panel.appendChild(linkList(m.anchors));
    const drawn = new Set(m.anchors.map((a) => QUAL[a]));
    const missing = m.about.filter((name) => !drawn.has(name));
    if (missing.length) panel.appendChild(el('p', 'qual', `${missing.join(', ')} (${S.notDrawn})`));
    if (!m.anchors.length && !m.about.length) panel.appendChild(el('p', 'qual', S.unanchored));
    panel.classList.add('open');
    panel.scrollTop = 0;
  }

  function refresh() { computeLit(); writeNodes(); writeEdges(); writeFocus(); writeMemories(); resetPulses(); renderRegions(); }
  function select(i, fly) {
    state.selected = i; state.selectedMem = -1;
    refresh();
    renderNode(i);
    if (fly) flyTo(POS[i * 3], POS[i * 3 + 1], POS[i * 3 + 2], Math.min(cam.dist, 1.6));
    try { history.replaceState(null, '', '#s=' + ID[i]); } catch (_) { /* a file URL may refuse */ }
  }
  function selectMemory(k, fly) {
    state.selectedMem = k; state.selected = -1;
    refresh();
    renderMemory(k);
    const m = MEM[k];
    if (fly) flyTo(m.pos[0], m.pos[1], m.pos[2], Math.min(cam.dist, 1.6));
    try { history.replaceState(null, '', '#m=' + m.id); } catch (_) { /* a file URL may refuse */ }
  }
  function clearSelection() {
    if (state.selected < 0 && state.selectedMem < 0 && state.region < 0) { flyTo(0, -0.08, 0, HOME_DIST); return; }
    if (state.selected >= 0 || state.selectedMem >= 0) { state.selected = -1; state.selectedMem = -1; } else { state.region = -1; }
    panel.classList.remove('open');
    refresh();
    try { history.replaceState(null, '', '#'); } catch (_) { /* a file URL may refuse */ }
  }

  // ---------------------------------------------------------------- the legend
  function renderRegions() {
    const ul = $('regions');
    ul.replaceChildren();
    regionOrder.slice(0, 60).forEach((r) => {
      const li = el('li', state.region === r ? 'on' : (state.region >= 0 ? 'off' : ''));
      li.appendChild(dot(REGION_RGB[r]));
      li.appendChild(el('span', 'nm', DATA.regions[r]));
      li.appendChild(el('span', 'n', fmt(REGION_SIZE[r])));
      li.title = DATA.regions[r];
      li.addEventListener('click', () => {
        state.selected = -1; state.selectedMem = -1; panel.classList.remove('open');
        state.region = state.region === r ? -1 : r;
        refresh();
        if (state.region >= 0) {
          let x = 0, y = 0, z = 0, n = 0;
          for (let i = 0; i < N; i++) if (REGION[i] === r) { x += POS[i * 3]; y += POS[i * 3 + 1]; z += POS[i * 3 + 2]; n++; }
          if (n) flyTo(x / n, y / n, z / n, 2.1);
        } else flyTo(0, -0.08, 0, HOME_DIST);
      });
      ul.appendChild(li);
    });
  }
  const toggleNames = { edges: S.tEdges, signals: S.tSignals, memories: S.tMemories, cortex: S.tCortex, labels: S.tLabels, rotate: S.tRotate };
  Object.keys(toggleNames).forEach((key) => {
    const label = el('label'), box = el('input');
    box.type = 'checkbox'; box.checked = state.show[key];
    box.addEventListener('change', () => { state.show[key] = box.checked; });
    label.append(box, document.createTextNode(toggleNames[key]));
    $('toggles').appendChild(label);
  });
  $('regions-title').textContent = S.regions;
  $('view-title').textContent = S.view;
  {
    const notes = [];
    if (TEST.some((t) => t)) notes.push(S.tests);
    // Memories are what makes this a second brain rather than a map, so say how to add one.
    if (MEM.length === 0 && N > 0) notes.push(S.noMem);
    $('legend-note').textContent = notes.join(' ');
  }

  // ---------------------------------------------------------------- header and notes
  $('repo').textContent = DATA.repo || '';
  {
    const stale = MEM.filter((m) => m.stale).length;
    const stats = $('stats');
    const part = (n, label) => { const s = el('span'); s.appendChild(el('b', '', fmt(n))); s.appendChild(document.createTextNode(' ' + label)); return s; };
    stats.append(part(DATA.files, S.files), document.createTextNode(' · '), part(DATA.symbols, S.symbols), document.createTextNode(' · '),
      part(DATA.edgesTotal, S.edges), document.createElement('br'), part(MEM.length, S.memories));
    if (stale) stats.append(document.createTextNode(' · '), part(stale, S.stale));
  }
  $('hint').innerHTML = S.hint;
  {
    const note = $('note');
    // Only a cap says anything here: module declarations are never drawn, so the index always
    // holds a few more symbols than the picture.
    if (N > 0 && N < (DATA.drawable || 0)) note.appendChild(el('div', '', S.cut(fmt(N), fmt(DATA.drawable))));
    note.appendChild(el('div', '', S.offline));
  }
  if (N === 0) showMessage(S.empty);

  // ---------------------------------------------------------------- search
  const search = $('search'), results = $('results'), historyEl = $('history');
  search.placeholder = S.search;
  const LOWER_NAME = NAME.map((s) => s.toLowerCase()), LOWER_QUAL = QUAL.map((s) => s.toLowerCase());
  const LOWER_PATH = Array.from({ length: N }, (_, i) => pathOf(i).toLowerCase()), LOWER_DOC = DOC.map((s) => s.toLowerCase());
  let found = [], active = 0;

  // Session history (sessionStorage)
  const HIST_KEY = 'pn-ultramemory-brain-history';
  let sessionHistory = [];
  try { sessionHistory = JSON.parse(sessionStorage.getItem(HIST_KEY) || '[]'); } catch (_) { sessionHistory = []; }
  function pushHistory(entry) {
    sessionHistory = sessionHistory.filter((h) => h.id !== entry.id);
    sessionHistory.unshift(entry);
    if (sessionHistory.length > 12) sessionHistory.length = 12;
    try { sessionStorage.setItem(HIST_KEY, JSON.stringify(sessionHistory)); } catch (_) { /* quota */ }
    renderHistory();
  }
  function renderHistory() {
    if (!historyEl) return;
    historyEl.replaceChildren();
    if (!sessionHistory.length) { historyEl.classList.remove('open'); return; }
    sessionHistory.forEach((h) => {
      const li = el('li');
      const d = el('span', 'dot');
      d.style.background = h.color || '#888';
      li.appendChild(d);
      li.appendChild(el('span', 'nm', h.name));
      li.appendChild(el('span', 'ts', h.ts || ''));
      li.addEventListener('mousedown', (ev) => {
        ev.preventDefault();
        if (h.type === 'mem') { const k = MEM.findIndex((m) => String(m.id) === h.id); if (k >= 0) selectMemory(k, true); }
        else { const i = ID.indexOf(h.id); if (i >= 0) select(i, true); }
        historyEl.classList.remove('open');
      });
      historyEl.appendChild(li);
    });
  }
  function highlightText(text, terms) {
    if (!terms.length) return document.createTextNode(text);
    const frag = document.createDocumentFragment();
    const lower = text.toLowerCase();
    let last = 0;
    const matches = [];
    for (const t of terms) {
      let idx = lower.indexOf(t, last);
      while (idx >= 0) { matches.push([idx, idx + t.length]); last = idx + t.length; idx = lower.indexOf(t, last); }
    }
    matches.sort((a, b) => a[0] - b[0]);
    // Merge overlapping
    const merged = [];
    for (const m of matches) {
      if (merged.length && m[0] <= merged[merged.length - 1][1]) merged[merged.length - 1][1] = Math.max(merged[merged.length - 1][1], m[1]);
      else merged.push([...m]);
    }
    let pos = 0;
    for (const [s, e] of merged) {
      if (s > pos) frag.appendChild(document.createTextNode(text.slice(pos, s)));
      const mark = document.createElement('mark');
      mark.textContent = text.slice(s, e);
      frag.appendChild(mark);
      pos = e;
    }
    if (pos < text.length) frag.appendChild(document.createTextNode(text.slice(pos)));
    return frag;
  }
  function runSearch() {
    const q = search.value.trim().toLowerCase();
    found = []; active = 0;
    if (!q) { results.classList.remove('open'); if (historyEl && sessionHistory.length) { historyEl.classList.add('open'); renderHistory(); } return; }
    if (historyEl) historyEl.classList.remove('open');
    const terms = q.split(/\s+/).filter(Boolean);
    for (let i = 0; i < N; i++) {
      let score = 0;
      for (const t of terms) {
        let s = 0;
        if (LOWER_NAME[i] === t) s = 120; else if (LOWER_NAME[i].startsWith(t)) s = 80; else if (LOWER_NAME[i].includes(t)) s = 55;
        else if (LOWER_QUAL[i].includes(t)) s = 38; else if (LOWER_PATH[i].includes(t)) s = 20; else if (LOWER_DOC[i].includes(t)) s = 8;
        if (!s) { score = 0; break; }
        score += s;
      }
      if (score) found.push({ node: i, score: score + Math.log2(1 + DEG[i]) * 3 });
    }
    MEM.forEach((m, k) => {
      const text = m.text.toLowerCase();
      if (terms.every((t) => text.includes(t) || m.kind.includes(t))) found.push({ mem: k, score: 45 });
    });
    found.sort((a, b) => b.score - a.score);
    found = found.slice(0, 14);
    renderResults(terms);
  }
  function renderResults(terms) {
    results.replaceChildren();
    if (!found.length) { results.appendChild(el('li', 'empty', S.noMatch)); results.classList.add('open'); return; }
    const t = terms || [];
    found.forEach((f, k) => {
      const li = el('li', k === active ? 'active' : '');
      if (f.mem != null) {
        const m = MEM[f.mem];
        li.appendChild(dot(m.stale ? STALE_RGB : MEM_RGB));
        const nm = el('span', 'nm');
        const txt = m.text.length > 70 ? m.text.slice(0, 69) + '…' : m.text;
        nm.appendChild(highlightText(txt, t));
        li.appendChild(nm);
        li.appendChild(el('span', 'pt', m.kind));
      } else {
        const i = f.node;
        li.appendChild(dot(REGION_RGB[REGION[i]]));
        const nm = el('span', 'nm');
        nm.appendChild(highlightText(QUAL[i], t));
        li.appendChild(nm);
        li.appendChild(el('span', 'pt', `${pathOf(i)}:${LINE[i]}`));
      }
      li.addEventListener('mousedown', (ev) => { ev.preventDefault(); choose(k); });
      results.appendChild(li);
    });
    results.classList.add('open');
  }
  function choose(k) {
    const f = found[k];
    if (!f) return;
    if (f.mem != null) selectMemory(f.mem, true); else select(f.node, true);
    results.classList.remove('open');
    search.blur();
  }
  search.addEventListener('input', runSearch);
  search.addEventListener('focus', () => { if (search.value.trim()) runSearch(); else if (historyEl && sessionHistory.length) { historyEl.classList.add('open'); renderHistory(); } });
  search.addEventListener('blur', () => setTimeout(() => { results.classList.remove('open'); if (historyEl) historyEl.classList.remove('open'); }, 120));
  search.addEventListener('keydown', (ev) => {
    if (ev.key === 'ArrowDown') { active = Math.min(found.length - 1, active + 1); renderResults(); ev.preventDefault(); }
    else if (ev.key === 'ArrowUp') { active = Math.max(0, active - 1); renderResults(); ev.preventDefault(); }
    else if (ev.key === 'Enter') { choose(active); ev.preventDefault(); }
    else if (ev.key === 'Escape') { search.value = ''; results.classList.remove('open'); if (historyEl) historyEl.classList.remove('open'); search.blur(); }
  });
  document.addEventListener('keydown', (ev) => {
    if (document.activeElement === search) return;
    if (ev.key === '/' || ((ev.metaKey || ev.ctrlKey) && ev.key.toLowerCase() === 'k')) { search.focus(); search.select(); ev.preventDefault(); }
    else if (ev.key === 'Escape') clearSelection();
    else if (ev.key === 'f' && state.selected >= 0) { const i = state.selected; flyTo(POS[i * 3], POS[i * 3 + 1], POS[i * 3 + 2], 1.25); }
    else if (ev.key === 'r') { state.show.rotate = !state.show.rotate; document.querySelectorAll('#toggles input')[5].checked = state.show.rotate; }
  });
  $('menu').addEventListener('click', () => $('legend').classList.toggle('open'));

  // ---------------------------------------------------------------- pointer
  const pointers = new Map();
  let drag = null, lastInput = performance.now(), pinch = 0;
  canvas.addEventListener('contextmenu', (ev) => ev.preventDefault());
  canvas.addEventListener('pointerdown', (ev) => {
    canvas.setPointerCapture(ev.pointerId);
    pointers.set(ev.pointerId, [ev.clientX, ev.clientY]);
    if (pointers.size === 2) { const [a, b] = [...pointers.values()]; pinch = Math.hypot(a[0] - b[0], a[1] - b[1]); }
    drag = { x: ev.clientX, y: ev.clientY, moved: 0, pan: ev.button === 2 || ev.shiftKey };
    canvas.classList.add('dragging');
    lastInput = performance.now();
  });
  canvas.addEventListener('pointermove', (ev) => {
    lastInput = performance.now();
    if (pointers.has(ev.pointerId)) pointers.set(ev.pointerId, [ev.clientX, ev.clientY]);
    if (pointers.size === 2) {
      const [a, b] = [...pointers.values()], d = Math.hypot(a[0] - b[0], a[1] - b[1]);
      if (pinch) goal.dist = Math.max(0.5, Math.min(8, goal.dist * pinch / d));
      pinch = d; if (drag) drag.moved = 99; return;
    }
    if (drag) {
      const dx = ev.clientX - drag.x, dy = ev.clientY - drag.y;
      drag.x = ev.clientX; drag.y = ev.clientY; drag.moved += Math.abs(dx) + Math.abs(dy);
      if (drag.pan) {
        const s = cam.dist * 0.0011, c = Math.cos(cam.theta), sn = Math.sin(cam.theta);
        goal.tx -= dx * s * c; goal.tz += dx * s * sn; goal.ty += dy * s;
      } else {
        goal.theta -= dx * 0.0055;
        goal.phi = Math.max(-1.35, Math.min(1.35, goal.phi + dy * 0.0045));
      }
      return;
    }
    const hit = pick(ev.clientX, ev.clientY);
    state.hovered = hit.node; state.hoveredMem = hit.mem;
    canvas.classList.toggle('pointing', hit.node >= 0 || hit.mem >= 0);
  });
  function endPointer(ev) {
    pointers.delete(ev.pointerId);
    if (pointers.size < 2) pinch = 0;
    if (!drag) return;
    canvas.classList.remove('dragging');
    if (drag.moved < 5 && pointers.size === 0) {
      const hit = pick(ev.clientX, ev.clientY);
      if (hit.mem >= 0) selectMemory(hit.mem, false);
      else if (hit.node >= 0) select(hit.node, false);
      else if (state.selected >= 0 || state.selectedMem >= 0) clearSelection();
    }
    if (pointers.size === 0) drag = null;
  }
  canvas.addEventListener('pointerup', endPointer);
  canvas.addEventListener('pointercancel', endPointer);
  canvas.addEventListener('dblclick', (ev) => {
    const hit = pick(ev.clientX, ev.clientY);
    if (hit.node >= 0) select(hit.node, true); else if (hit.mem >= 0) selectMemory(hit.mem, true);
  });
  canvas.addEventListener('wheel', (ev) => {
    ev.preventDefault();
    lastInput = performance.now();
    goal.dist = Math.max(0.5, Math.min(8, goal.dist * Math.exp(ev.deltaY * 0.0012)));
  }, { passive: false });

  // ---------------------------------------------------------------- the loop
  const reduceMotion = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  if (reduceMotion) { simulate(SIM_STEPS); state.show.rotate = false; document.querySelectorAll('#toggles input')[5].checked = false; }
  refresh();
  {
    const m = /^#(s|m)=(.+)$/.exec(location.hash || '');
    if (m && m[1] === 's') { const i = ID.indexOf(m[2]); if (i >= 0) select(i, true); }
    if (m && m[1] === 'm') { const k = MEM.findIndex((x) => String(x.id) === m[2]); if (k >= 0) selectMemory(k, true); }
  }
  let last = performance.now();
  function frame() {
    // One clock for everything: the time a frame is handed is not on the same base as
    // performance.now() in every browser, and a negative step would run signals backwards.
    const now = performance.now();
    const dt = Math.max(0, Math.min(0.05, (now - last) / 1000));
    last = now;
    if (simStep < SIM_STEPS) {
      simulate(N > 4000 ? 2 : 4);
      writeNodes(); writeEdges(); writeFocus(); writeMemories();
    }
    if (state.show.rotate && now - lastInput > 2500 && !drag) goal.theta += dt * 0.07;
    updateCamera();
    gl.clearColor(0.016, 0.02, 0.047, 1);
    gl.clear(gl.COLOR_BUFFER_BIT);
    gl.disable(gl.DEPTH_TEST);
    gl.enable(gl.BLEND);
    gl.blendFunc(gl.ONE, gl.ONE);
    const fog = new Float32Array([cam.dist - 0.9, cam.dist + 1.1]);

    gl.useProgram(lineProg);
    gl.uniformMatrix4fv(LU.uMVP, false, MVP);
    gl.uniform2fv(LU.uFog, fog);
    if (state.show.edges) { gl.uniform1f(LU.uDim, 1); drawLines(B.edges); }
    gl.uniform1f(LU.uDim, 1); drawLines(B.focus);
    if (state.show.memories) drawLines(B.memLines);

    gl.useProgram(pointProg);
    gl.uniformMatrix4fv(PU.uMVP, false, MVP);
    gl.uniform1f(PU.uScale, SCALE);
    gl.uniform1f(PU.uTime, now / 1000);
    gl.uniform2fv(PU.uFog, fog);
    if (state.show.cortex) drawPoints(B.cortex);
    drawPoints(B.nodes);
    if (state.show.memories) drawPoints(B.mem);
    if (state.show.signals && !reduceMotion) { writePulses(dt); drawPoints(B.pulses); }
    const haloAt = state.selected >= 0 ? [POS[state.selected * 3], POS[state.selected * 3 + 1], POS[state.selected * 3 + 2]] : null;
    if (haloAt) {
      const beat = 0.5 + 0.5 * Math.sin(now / 260);
      upload(B.halo, new Float32Array([haloAt[0], haloAt[1], haloAt[2], 0.49, 0.96, 1, 0.07 + 0.02 * beat, 0.8, 1]), POINT_STRIDE);
      drawPoints(B.halo);
    }
    drawLabels();
    requestAnimationFrame(frame);
  }
  requestAnimationFrame(frame);
})();
